// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class FINAL_TRANSECT
{
    public int objectid { get; set; }

    public int? join_count { get; set; }

    public int? target_fid { get; set; }

    public decimal? objectid_1 { get; set; }

    public decimal? baselineid { get; set; }

    public decimal? transorder { get; set; }

    public decimal? transedit { get; set; }

    public decimal? transectid { get; set; }

    public decimal? shrcount { get; set; }

    public decimal? lrr { get; set; }

    public decimal? lr2 { get; set; }

    public decimal? lci { get; set; }

    public decimal? lse { get; set; }

    public decimal? epr { get; set; }

    public decimal? eprunc { get; set; }

    public decimal? nsm { get; set; }

    public decimal? sce { get; set; }

    public decimal? wlr { get; set; }

    public decimal? wr2 { get; set; }

    public decimal? wci { get; set; }

    public decimal? wse { get; set; }

    public decimal? tcd { get; set; }

    public decimal? distancetobase2007 { get; set; }

    public short? uncertainty { get; set; }

    public string date_ { get; set; }

    public decimal? shape_length_1 { get; set; }

    public decimal? dt_to_shoreline_2007 { get; set; }

    public decimal? dt_to_shoreline_2013 { get; set; }

    public decimal? dt_to_shoreline_2018 { get; set; }

    public decimal? dt_to_shoreline_2023 { get; set; }

    public Geometry shape { get; set; }
}