// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class FINAL_TRANSECT
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public decimal? TransectId { get; set; }

    public decimal? ShrCount { get; set; }

    public decimal? LRR { get; set; }

    public decimal? LR2 { get; set; }

    public decimal? LCI { get; set; }

    public decimal? LSE { get; set; }

    public decimal? EPR { get; set; }

    public decimal? EPRunc { get; set; }

    public decimal? NSM { get; set; }

    public decimal? SCE { get; set; }

    public decimal? WLR { get; set; }

    public decimal? WR2 { get; set; }

    public decimal? WCI { get; set; }

    public decimal? WSE { get; set; }

    public decimal? TCD { get; set; }

    public short? UNCERTAINTY { get; set; }

    public decimal? Shape_Length_1 { get; set; }

    public decimal? Dt_To_Shoreline_2007 { get; set; }

    public decimal? Dt_To_Shoreline_2013 { get; set; }

    public decimal? Dt_To_Shoreline_2018 { get; set; }

    public decimal? Dt_To_Shoreline_2023 { get; set; }
}