// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Graduation_Project.Models;

public partial class Final_ProjectContext : DbContext
{
    public Final_ProjectContext(DbContextOptions<Final_ProjectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BUILDING> BUILDINGs { get; set; }
    public virtual DbSet<Account> Accounts { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<UserLocation> UserLocations { get; set; }

    public virtual DbSet<FINAL_TRANSECT> FINAL_TRANSECTs { get; set; }

    public virtual DbSet<SHORELINE_1986_2023__PROJECT> SHORELINE_1986_2023__PROJECTs { get; set; }

    public virtual DbSet<SHORELINE_1986_SEGMENTED_PROJECT> SHORELINE_1986_SEGMENTED_PROJECTs { get; set; }

    public virtual DbSet<SHORELINE_2007_SEGMENTED_PROJECT> SHORELINE_2007_SEGMENTED_PROJECTs { get; set; }

    public virtual DbSet<SHORELINE_2013_SEGMENTED_PROJECT> SHORELINE_2013_SEGMENTED_PROJECTs { get; set; }

    public virtual DbSet<SHORELINE_2018_SEGMENTED_PROJECT> SHORELINE_2018_SEGMENTED_PROJECTs { get; set; }

    public virtual DbSet<SHORELINE_2023_AFTER> SHORELINE_2023_AFTERs { get; set; }

    public virtual DbSet<SHORELINE_2023_CVI_1KM> SHORELINE_2023_CVI_1KMs { get; set; }

    public virtual DbSet<SHORELINE_2023_SEGMENTED_PROJECT> SHORELINE_2023_SEGMENTED_PROJECTs { get; set; }

    public virtual DbSet<SHORELINE_2023_SEGMEN_BUFFER> SHORELINE_2023_SEGMEN_BUFFERs { get; set; }

    public virtual DbSet<SHORELINE_RATES_SEGMENTED_CLOSEST> SHORELINE_RATES_SEGMENTED_CLOSESTs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BUILDING>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__BUILDING__F4B70D85C07A1108");

            entity.ToTable("BUILDINGS");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.ADDR_CITY).HasMaxLength(80);
            entity.Property(e => e.ADDR_NUM).HasMaxLength(80);
            entity.Property(e => e.ADDR_ST).HasMaxLength(91);
            entity.Property(e => e.BLDG_TYPE).HasMaxLength(80);
            entity.Property(e => e.BLDG_USE).HasMaxLength(80);
            entity.Property(e => e.CENT_X).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.CENT_Y).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.DIST_COAST).HasMaxLength(80);
            entity.Property(e => e.ELEVATION).HasMaxLength(80);
            entity.Property(e => e.EST_OCCUP).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.EST_VALUE).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.HEIGHT).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LEVELS).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.NAME).HasMaxLength(92);
            entity.Property(e => e.PERIM_M).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.STATUS).HasMaxLength(80);
            entity.Property(e => e.Shape).HasColumnType("geometry");
            entity.Property(e => e.VAL_USD_M2).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.VULN_SCORE).HasColumnType("numeric(38, 8)");
        });

        modelBuilder.Entity<FINAL_TRANSECT>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__FINAL_TR__F4B70D85FD30F7B2");

            entity.ToTable("FINAL_TRANSECT");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.Dt_To_Shoreline_2007).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Dt_To_Shoreline_2013).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Dt_To_Shoreline_2018).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Dt_To_Shoreline_2023).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.EPR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.EPRunc).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LCI).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LR2).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LRR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LSE).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.NSM).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.SCE).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Shape).HasColumnType("geometry");
            entity.Property(e => e.Shape_Length_1).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.ShrCount).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.TCD).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.TransectId).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WCI).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WLR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WR2).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WSE).HasColumnType("numeric(38, 8)");
        });

        modelBuilder.Entity<SHORELINE_1986_2023__PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E6329345BDFF");

            entity.ToTable("SHORELINE_1986_2023__PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.merge_src).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_1986_SEGMENTED_PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E63201F0D9DF");

            entity.ToTable("SHORELINE_1986_SEGMENTED_PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.dt_to_shoreline_2007).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.dt_to_shoreline_2013).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.dt_to_shoreline_2018).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.dt_to_shoreline_2023).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.shape).HasColumnType("geometry");
        });


        modelBuilder.Entity<SHORELINE_2007_SEGMENTED_PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E63242FC7AA9");

            entity.ToTable("SHORELINE_2007_SEGMENTED_PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2013_SEGMENTED_PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E6323116B3B0");

            entity.ToTable("SHORELINE_2013_SEGMENTED_PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2018_SEGMENTED_PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E632BC5E966C");

            entity.ToTable("SHORELINE_2018_SEGMENTED_PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_AFTER>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__SHORELIN__F4B70D855E9F4AC8");

            entity.ToTable("SHORELINE_2023_AFTER");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.CVI_Classify).HasMaxLength(255);
            entity.Property(e => e.EPR_Category).HasMaxLength(255);
            entity.Property(e => e.Shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_CVI_1KM>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E632B67F7F4E");

            entity.ToTable("SHORELINE_2023_CVI_1KM");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.cvi_classify).HasMaxLength(255);
            entity.Property(e => e.epr_category).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });


        modelBuilder.Entity<SHORELINE_2023_SEGMENTED_PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E632AE2817F0");

            entity.ToTable("SHORELINE_2023_SEGMENTED_PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_SEGMEN_BUFFER>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__SHORELIN__F4B70D8510A6984E");

            entity.ToTable("SHORELINE_2023_SEGMEN_BUFFER");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.BUFF_DIST).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_RATES_SEGMENTED_CLOSEST>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__SHORELIN__F4B70D850BAAAE51");

            entity.ToTable("SHORELINE_RATES_SEGMENTED_CLOSEST");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.AREA).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.BUFF_DIST).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.BaselineID).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.COUNT_).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.EPR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.EPRunc).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LCI).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LR2).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LRR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LSE).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.MEAN).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.NSM).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.ObjectID_12_13).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.SCE).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Shape).HasColumnType("geometry");
            entity.Property(e => e.Shape_Length_1).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.ShrCount).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.TCD).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.TransEdit).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.TransOrder).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.TransectId).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WCI).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WLR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WR2).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.WSE).HasColumnType("numeric(38, 8)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}