// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_RATES_SEGMENTED_CLOSEST
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public int? Join_Count { get; set; }

    public int? TARGET_FID { get; set; }

    public int? InLine_FID { get; set; }

    public int? ORIG_FID { get; set; }

    public int? ORIG_SEQ { get; set; }

    public decimal? BUFF_DIST { get; set; }

    public int? OBJECTID_1 { get; set; }

    public int? OBJECTID_12 { get; set; }

    public decimal? COUNT_ { get; set; }

    public decimal? AREA { get; set; }

    public decimal? MEAN { get; set; }

    public decimal? ObjectID_12_13 { get; set; }

    public decimal? BaselineID { get; set; }

    public decimal? TransOrder { get; set; }

    public decimal? TransEdit { get; set; }

    public decimal? TransectId { get; set; }

    public decimal? ShrCount { get; set; }

    public decimal? LRR { get; set; }

    public decimal? LR2 { get; set; }

    public decimal? LCI { get; set; }

    public decimal? LSE { get; set; }

    public decimal? EPR { get; set; }

    public decimal? EPRunc { get; set; }

    public decimal? NSM { get; set; }

    public decimal? SCE { get; set; }

    public decimal? WLR { get; set; }

    public decimal? WR2 { get; set; }

    public decimal? WCI { get; set; }

    public decimal? WSE { get; set; }

    public decimal? TCD { get; set; }

    public decimal? Shape_Length_1 { get; set; }
}