// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_POINTS_100M
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public decimal? Coastal_Slope { get; set; }

    public decimal? Current_Position_X { get; set; }

    public decimal? Current_Position_Y { get; set; }

    public decimal? Elevation { get; set; }

    public decimal? LRR { get; set; }

    public decimal? Position_2030_X { get; set; }

    public decimal? Position_2030_Y { get; set; }

    public decimal? Position_2035_X { get; set; }

    public decimal? Position_2035_Y { get; set; }

    public decimal? Position_2040_X { get; set; }

    public decimal? Position_2040_Y { get; set; }

    public decimal? Position_2045_X { get; set; }

    public decimal? Position_2045_Y { get; set; }

    public decimal? Position_2050_X { get; set; }

    public decimal? Position_2050_Y { get; set; }

    public decimal? Position_2100_X { get; set; }

    public decimal? Position_2100_Y { get; set; }

    public decimal? Sea_Level_Rise_Trend_mm_year { get; set; }

    public decimal? NSM { get; set; }
}