// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_1986_2023__PROJECT_FINAL
{
    public int objectid { get; set; }

    public short? uncertainty { get; set; }

    public string date_ { get; set; }

    public string merge_src { get; set; }

    public Geometry shape { get; set; }
}