// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_CVI_1KM
{
    public int objectid { get; set; }

    public int? orig_seq { get; set; }

    public short? slope_rank { get; set; }

    public short? lrr_erosion_rank { get; set; }

    public short? epr_rank { get; set; }

    public string epr_category { get; set; }

    public short? tidal_rank { get; set; }

    public short? wave_height_rank { get; set; }

    public short? cvi_rank { get; set; }

    public string cvi_classify { get; set; }

    public Geometry shape { get; set; }
}