// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_BASELINE
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public int? ID { get; set; }

    public decimal? SHAPE_LENGTH1 { get; set; }
}