// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_AFTER
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public int? ORIG_SEQ { get; set; }

    public short? Slope_Rank { get; set; }

    public short? LRR_Erosion_Rank { get; set; }

    public short? EPR_Rank { get; set; }

    public string EPR_Category { get; set; }

    public short? Tidal_Rank { get; set; }

    public short? Wave_Height_Rank { get; set; }

    public short? CVI_Rank { get; set; }

    public string CVI_Classify { get; set; }
}