// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_SEGMENTED_PROJECT
{
    public int objectid { get; set; }

    public string date_ { get; set; }

    public short? uncertainty { get; set; }

    public Geometry shape { get; set; }
}