// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_POINTS_100M
{
    public int objectid { get; set; }

    public decimal? coastal_slope { get; set; }

    public decimal? current_position_x { get; set; }

    public decimal? current_position_y { get; set; }

    public decimal? elevation { get; set; }

    public decimal? lrr { get; set; }

    public decimal? position_2030_x { get; set; }

    public decimal? position_2030_y { get; set; }

    public decimal? position_2035_x { get; set; }

    public decimal? position_2035_y { get; set; }

    public decimal? position_2040_x { get; set; }

    public decimal? position_2040_y { get; set; }

    public decimal? position_2045_x { get; set; }

    public decimal? position_2045_y { get; set; }

    public decimal? position_2050_x { get; set; }

    public decimal? position_2050_y { get; set; }

    public decimal? position_2100_x { get; set; }

    public decimal? position_2100_y { get; set; }

    public decimal? sea_level_rise_trend_mm_year { get; set; }

    public decimal? nsm { get; set; }

    public Geometry shape { get; set; }
}