// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2013_POINTS_100M
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public int? ORIG_FID { get; set; }

    public string Name { get; set; }

    public string FolderPath { get; set; }

    public int? SymbolID { get; set; }

    public short? AltMode { get; set; }

    public decimal? Base { get; set; }

    public short? Clamped { get; set; }

    public short? Extruded { get; set; }

    public string Snippet { get; set; }

    public string PopupInfo { get; set; }

    public int? InLine_FID { get; set; }
}