// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_1986_SEGMENTED_PROJECT
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public short? UNCERTAINTY { get; set; }

    public string DATE_ { get; set; }

    public decimal? Dt_To_Shoreline_2007 { get; set; }

    public decimal? Dt_To_Shoreline_2013 { get; set; }

    public decimal? Dt_To_Shoreline_2018 { get; set; }

    public decimal? Dt_To_Shoreline_2023 { get; set; }
}