// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINES_1986_2100
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public short? Year { get; set; }
}