// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_BASELINE
{
    public int objectid { get; set; }

    public int? id { get; set; }

    public decimal? shape_length1 { get; set; }

    public Geometry shape { get; set; }
}