// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINES_1986_2023
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public short? UNCERTAINTY { get; set; }

    public string DATE_ { get; set; }

    public string MERGE_SRC { get; set; }

    public decimal? SHAPE_LENGTH1 { get; set; }
}