// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_SEGMEN_BUFFER
{
    public int OBJECTID { get; set; }

    public Geometry Shape { get; set; }

    public int? InLine_FID { get; set; }

    public int? ORIG_FID { get; set; }

    public int? ORIG_SEQ { get; set; }

    public decimal? BUFF_DIST { get; set; }
}