// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_2023_POINTS_250M
{
    public int objectid { get; set; }

    public int? orig_fid { get; set; }

    public string name { get; set; }

    public string folderpath { get; set; }

    public int? symbolid { get; set; }

    public short? altmode { get; set; }

    public decimal? _base { get; set; }

    public short? clamped { get; set; }

    public short? extruded { get; set; }

    public string snippet { get; set; }

    public string popupinfo { get; set; }

    public int? inline_fid { get; set; }

    public Geometry shape { get; set; }
}