// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class SHORELINE_1986_SEGMENTED_PROJECT
{
    public int objectid { get; set; }

    public short? uncertainty { get; set; }

    public string date_ { get; set; }

    public decimal? dt_to_shoreline_2007 { get; set; }

    public decimal? dt_to_shoreline_2013 { get; set; }

    public decimal? dt_to_shoreline_2018 { get; set; }

    public decimal? dt_to_shoreline_2023 { get; set; }

    public Geometry shape { get; set; }
}